[package]
name = "abac"
version = "0.1.0"
edition = "2021"


[[bin]]
name = "abac"
path = "src/main.rs"

[lib]
name = "abac"
path = "lib/mod.rs"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
toml = "0.8.20"
